zipkin:
  collector:
    rabbitmq:
      addresses: paycloud-mq-rabbit:5672
      username: guest
      password: guest
      queue: zipkin

spring:
    rabbitmq:
        address: paycloud-mq-rabbit:5672
        password: guest
        username: guest
