spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  rabbitmq:
      address: paycloud-mq-rabbit:5672
      password: guest
      username: guest
  zipkin:
    locator:
      discovery:
        enabled: true
  cloud:
      gateway:
          discovery:
              locator:
                  enabled: true
                  lower-case-service-id: true              