spring:
  security:
    user:
      name: root
      password: root
  boot:
    admin:
      monitor:
        status-interval: 60000

turbine:
  app-config: paycloud-gateway #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称