spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  rabbitmq:
      address: paycloud-mq-rabbit:5672
      password: '{cipher}AQBu0emZof9+JS/Awbk9uVOlkfkJQ7iZADezEm3+u/VDK/2alvpZoBPSP95DCykciuetOvdQCjZaeRAr5EjSFHB+I6oMF8STs+rCJXVc5KNUD9Bw9DJ/2aqSLWdDx1vahcdgr0cRhaMHu/cTO/PAcqHC26lgZUg6R2Wh3UgpGKEhxHOZpL11dWbHFU954tPaMfwXW9HNRSVUHtP58dZ4KAMXBxl01QcpofViv9Cee3S5cf9e5SRfrk90ml+3poX4L8oWyLWESgtFL1kxpJpeVp+nnf2kN7Ts0wOiUtr1tOn27vov4SVPMoJdsSfV06kuuvIVhtlahsyBSV+QXUGbxZm5K2V01LjQyft2hbqlGdWcyhdvusCEFDiH3Aq0a5OA8fU='
      username: guest
  zipkin:
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0        
  cloud:
      gateway:
          discovery:
              locator:
                  enabled: true
                  lower-case-service-id: true
          routes:
          - id:
              zipbin-route
            uri:
              http://localhost:8003/
            predicates:
              - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          - id:
                uac
            uri: lb://paycloud-oauth2-server
            predicates:
              - Path=/oauth/**,/user
            filters:
              - TokenRelay= 
security:
  oauth2:
    client:
      clientId: paycloud-gateway
      clientSecret: paycloudGateWaySecret
      access-token-uri: http://paycloud-gateway:8004/uac/oauth/token
      user-authorization-uri: http://paycloud-gateway:8004/uac/oauth/authorize
    resource:
      user-info-uri: http://paycloud-gateway:8004/uac/user
      prefer-token-info: false

